Chore: fix openssl security fix
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at hashOf (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1890023)
    at ncc (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1894655)
    at runCmd (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:52268)
    at 819 (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48838)
    at __webpack_require__ (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59076)
    at /Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59288
    at /Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59349
    at Object.<anonymous> (/Users/username/development/esy/github-action/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

ncc constraint needs to be relaxed